### GET all
GET http://localhost:3003/api/blogs

### GET id 1
GET http://localhost:3003/api/blogs/1

### GET author test_author blogs
GET http://localhost:3003/api/blogs/author/test_author

### like id 51
POST http://localhost:3003/api/blogs/like/51

### POST
POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdF91c2VyX3Jlc3QiLCJ1c2VyX2lkIjoyLCJpYXQiOjE3MjgwMzIyMjYsImV4cCI6MTcyODAzNTgyNn0.lLNhPoj3NbhSrngk87UX9YQ0zFNBo9He7mncojKSWtM

{
    "user_id": 2,
    "title": "test_title",
    "author": "test_author",
    "url": "www.test_address.fi"
}

### POST FAIL
POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "wtf is dis",
    "author": "dude",
    "url": "www.wtf.fi",
    "THINGY": 123123
}

### DELETE id
DELETE http://localhost:3003/api/blogs/36
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdF91c2VyX3Jlc3QiLCJ1c2VyX2lkIjoyLCJpYXQiOjE3MjgwMzIyMjYsImV4cCI6MTcyODAzNTgyNn0.lLNhPoj3NbhSrngk87UX9YQ0zFNBo9He7mncojKSWtM