### POST
POST http://localhost:3003/api/users
content-type: application/json

{
    "name": "test_user_rest",
    "password": "test_user_password_rest"
}

### POST FAIL
POST http://localhost:3003/api/users
content-type: application/json

{
    "name": "test_user",
    "password": "shrt"
}

### POST LOGIN
POST http://localhost:3003/api/users/login
content-type: application/json

{
    "name": "test_user_rest",
    "password": "test_user_password_rest"
}